# Example config file for sweep.sbatch.py.

app: 'path/to/polychrom/python/script'
out_dir: 'path/to/output/directory'
plots_dir: 'path/to/plots/directory'
maps_dir: 'path/to/map/data/directory'
replicates: 10
cli_params:
    --param1:
        - 1
        - 2
        - 3
    --param2:
        - 'value1'
        - 'value2'
    --param3:
        - true
        - false